spring:
  #静态资源处理
  resources:
    #启动默认资源静态处理,默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存响应时间，单位是秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      # 启用资源链，默认禁用
      enabled: true
      # 启用压缩资源(gzip,brotli)，默认禁用
      compressed: true
      # 启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/


  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000(10分钟)，这里给半小时
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的链接自动提交
      auto-commit: true
      # 最大存活时间半个小时，0表示永久存活，默认1800000
      max-lifetime: 180000
      # 连接超时时间，默认3000(30秒)
      connection-timeout: 30000
      # 心跳机制，测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redis配置
  redis:
    #服务器地址
    host: 192.168.109.130
    # 端口
    port: 6379
    # 操作数据库
    database: 0
    #超时时间
    timeout: 10000ms
    #lettuce连接池做相应的配置
    lettuce:
      pool:
        #最大连接数，默认是8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8，根据实际项目需求定
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
  rabbitmq:
    # 服务器
    host: 192.168.109.130
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口

    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完在继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        # 被拒绝是重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000ms
        # 重试次数，默认为3
        max-attempts: 3
        # 重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        # 重试的间隔乘数。比如配2.0，第一次就等10s，第二次等20s，第三次等40s
        multiplier: 1


# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件,文件放在resource目录下mapper下
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.example.skillmall.pojo

# Mybatis sql打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.example.seckill.mapper: debug


